import { describe, expect, it } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const BINDINGS_DIR = join(__dirname, "..", "src", "generated", "bindings");

function binding(name: string): string {
  return readFileSync(join(BINDINGS_DIR, `${name}.ts`), "utf8");
}

/** The binding with doc comments stripped, so assertions see fields only. */
function fieldsOf(name: string): string {
  return binding(name).replace(/\/\*[\s\S]*?\*\//g, "");
}

/**
 * Rust owns every type that crosses the boundary; TypeScript consumes generated
 * bindings. These assertions fail when someone edits a binding by hand, deletes
 * one, or changes a Rust type without re-running `cargo test` to regenerate.
 */
describe("generated ts-rs bindings", () => {
  // The runtime and connection data model (checkpoint 2).
  const runtimeTypes = [
    "ConnectionHealth",
    "ConnectionHealthStatus",
    "ConnectionSummary",
    "AgentInstallation",
    "AgentKind",
    "Connection",
    "ConnectionModel",
    "DiscoverySource",
    "PathSource",
    "Provider",
    "RuntimeKind",
    "RuntimeRef",
    "UnresolvedReason",
    "VerificationResult",
    "Workspace",
    "WorkspaceAvailability",
  ];

  // The ACP host (checkpoint 3).
  const acpTypes = [
    "AcpLaunchRequest",
    "AcpSessionStart",
    "AcpError",
    "AcpEvent",
    "AgentAuthMethod",
    "AgentAuthKind",
    "AgentCapabilitySet",
    "AgentDescriptor",
    "AuthenticationState",
    "InstallationState",
    "ChoiceKind",
    "PermissionChoice",
    "PermissionDecision",
    "PermissionRequest",
    "PlanStep",
    "ProcessState",
    "ProcessStatus",
    "Recoverability",
    "SessionRecord",
    "ToolActivity",
    "ToolLocation",
    "ToolStatus",
    "TurnEnd",
    "UnrecoverableReason",
  ];

  // Codex setup (checkpoint 4).
  const codexTypes = [
    "AdapterInstallPlan",
    "AdapterInstallResult",
    "AdapterSource",
    "CodexDetection",
    "CodexPathOverride",
    "CodexSettings",
    "CodexSetupState",
    "CodexSetupView",
    "PrimaryAction",
  ];

  // Claude setup (checkpoint 5).
  const claudeTypes = [
    "ClaudeDetection",
    "ClaudeInstallKind",
    "ClaudeSettings",
    "ClaudeSetupState",
    "ClaudeSetupView",
    "NodeRequirement",
  ];

  // Direct chat provider runtime (checkpoint 6).
  const chatRuntimeTypes = [
    "ChatRuntimeError",
    "ChatRuntimeEvent",
    "ChatRuntimeStatus",
    "ChatUsage",
    "ConnectionValidation",
  ];

  const expected = [
    ...runtimeTypes,
    ...acpTypes,
    ...codexTypes,
    ...claudeTypes,
    ...chatRuntimeTypes,
  ];

  it("exports every runtime type", () => {
    const present = readdirSync(BINDINGS_DIR)
      .filter((file) => file.endsWith(".ts"))
      .map((file) => file.replace(/\.ts$/, ""))
      .sort();
    expect(present).toEqual([...expected].sort());
  });

  it("marks every binding as generated so nobody edits one by hand", () => {
    for (const name of expected) {
      expect(binding(name), name).toContain("Do not edit this file manually");
    }
  });

  it("keeps the runtime reference a tagged union with an explicit discriminant", () => {
    const source = binding("RuntimeRef");
    expect(source).toContain('"kind": "chat-model"');
    expect(source).toContain('"kind": "coding-agent"');
    expect(source).toContain('"kind": "unresolved"');

    // The chat family carries a connection and a model.
    expect(source).toMatch(/"kind": "chat-model"[^}]*connection_id: string/);
    expect(source).toMatch(/"kind": "chat-model"[^}]*model_id: string/);

    // The coding-agent family carries an installation, a kind, a workspace, and
    // an optional session.
    expect(source).toMatch(/"kind": "coding-agent"[^}]*installation_id: string/);
    expect(source).toMatch(/"kind": "coding-agent"[^}]*agent_kind: AgentKind/);
    expect(source).toMatch(/"kind": "coding-agent"[^}]*workspace_id: string/);
    expect(source).toMatch(/"kind": "coding-agent"[^}]*acp_session_id\?/);
  });

  it("never exposes a credential on a connection, only a reference", () => {
    const source = fieldsOf("Connection");
    expect(source).toContain("secret_ref: string | null");
    // A credential-bearing field would have to be named something; none of
    // these exist, and `secret_ref` is a handle rather than a value.
    expect(source).not.toMatch(/\bapi_key\b/);
    expect(source).not.toMatch(/\bpassword\b/i);
    expect(source).not.toMatch(/\btoken\b/i);
    expect(source).not.toMatch(/(^|[\s,{])secret\s*:/);
  });

  it("keeps the model record's documented fields", () => {
    const source = binding("ConnectionModel");
    for (const field of [
      "remote_id",
      "display_name",
      "capabilities",
      "enabled",
      "aliases",
      "metadata",
      "discovery_source",
    ]) {
      expect(source, field).toContain(field);
    }
  });

  it("keeps provider payloads behind one bounded metadata field", () => {
    const source = binding("ChatRuntimeEvent");
    for (const kind of [
      "message.delta",
      "reasoning.delta",
      "tool.started",
      "tool.updated",
      "tool.completed",
      "usage.updated",
      "status.changed",
      "completed",
      "failed",
    ]) {
      expect(source).toContain(`"type": "${kind}"`);
    }
    expect(source).not.toMatch(/openai|anthropic|gemini|ollama/i);
  });

  it("keeps the installation record's documented fields", () => {
    const source = binding("AgentInstallation");
    for (const field of [
      "agent_kind",
      "executable_path",
      "path_source",
      "detected_versions",
      "last_verification",
      "last_verified_at",
    ]) {
      expect(source, field).toContain(field);
    }
    // Launch arguments are an array, never a shell string.
    expect(source).toContain("launch_args: Array<string>");
  });

  it("keeps the workspace record's documented fields", () => {
    const source = binding("Workspace");
    for (const field of ["path", "display_name", "last_validated_at", "availability"]) {
      expect(source, field).toContain(field);
    }
  });

  it("emits numbers rather than bigints for ordering fields", () => {
    expect(binding("Connection")).toContain("position: number");
  });

  it("keeps every ACP capability explicit, with none defaulted away", () => {
    const source = fieldsOf("AgentCapabilitySet");
    for (const capability of [
      "load_session",
      "resume_session",
      "permission_requests",
      "filesystem",
      "terminal",
      "background_terminal",
      "images",
      "context_references",
      "plans",
      "slash_commands",
      "mcp",
    ]) {
      // Non-optional booleans: an agent's capability is always stated, never
      // left undefined for the UI to guess at.
      expect(source, capability).toContain(`${capability}: boolean`);
    }
  });

  it("keeps ACP session activity a tagged union React can switch on", () => {
    const source = binding("AcpEvent");
    for (const variant of [
      "session-started",
      "agent-message",
      "agent-thought",
      "tool-activity",
      "permission-requested",
      "permission-withdrawn",
      "turn-ended",
      "failed",
      "lagged",
      "meta",
    ]) {
      expect(source, variant).toContain(`"type": "${variant}"`);
    }
  });

  it("keeps every ACP error variant actionable", () => {
    const source = binding("AcpError");
    for (const variant of [
      "resolve",
      "spawn",
      "initialize",
      "timeout",
      "request-timeout",
      "idle-timeout",
      "hard-turn-timeout",
      "write-timeout",
      "cancel-drain-timeout",
      "agent-exited",
      "protocol",
      "transport",
      "agent",
      "cancelled",
    ]) {
      expect(source, variant).toContain(`"kind": "${variant}"`);
    }
  });

  it("renders permission choices from the agent's own options", () => {
    const request = fieldsOf("PermissionRequest");
    expect(request).toContain("choices: Array<PermissionChoice>");
    expect(request).toContain("command: string | null");
    expect(request).toContain("working_directory: string | null");

    // The agent's option id is what gets sent back, so it has to survive.
    expect(fieldsOf("PermissionChoice")).toContain("option_id: string");

    // Cancelled is a distinct outcome, never collapsed into an allow.
    const decision = binding("PermissionDecision");
    expect(decision).toContain('"outcome": "cancelled"');
    expect(decision).toContain('"outcome": "selected"');
  });

  it("keeps the Codex setup axes explicit", () => {
    const source = binding("CodexSetupState");
    for (const state of [
      "not-installed",
      "needs-initialize",
      "authentication-required",
      "cli-login-required",
      "config-invalid",
      "cli-missing",
      "adapter-missing",
      "adapter-outdated",
      "ready",
      "crashed",
    ]) {
      expect(source, state).toContain(`"state": "${state}"`);
    }
    // Version incompatibility is deliberately not a first-class state: the
    // adapter ships a compatible Codex, and its own error is what surfaces.
    expect(source).not.toMatch(/version-incompat/i);
    // Poly UI does not authenticate anyone — there is no method list, no
    // capability set, and no signed-in-with field on the card's state.
    expect(source).not.toContain("auth_methods");
    expect(source).not.toContain("capabilities");
  });

  it("keeps Claude installation shape explicit", () => {
    const detection = binding("ClaudeDetection");
    expect(detection).toContain("install_kind: ClaudeInstallKind | null");
    expect(detection).toContain("node: NodeRequirement");

    const setup = binding("ClaudeSetupState");
    for (const state of [
      "not-installed",
      "needs-initialize",
      "authentication-required",
      "cli-login-required",
      "config-invalid",
      "cli-missing",
      "adapter-missing",
      "adapter-outdated",
      "ready",
      "crashed",
    ]) {
      expect(setup).toContain(`"state": "${state}"`);
    }
    expect(setup).not.toContain("auth_methods");
    expect(setup).not.toContain("capabilities");
  });

  it("states why a session cannot be restored rather than only that it cannot", () => {
    const source = binding("Recoverability");
    expect(source).toContain('"status": "recoverable"');
    expect(source).toContain('"status": "unrecoverable"');
    expect(source).toContain("reason: UnrecoverableReason");

    const reasons = binding("UnrecoverableReason");
    for (const reason of [
      "agent-cannot-load-sessions",
      "stale-session-id",
      "workspace-missing",
      "process-crashed",
    ]) {
      expect(reasons, reason).toContain(`"${reason}"`);
    }
  });
});
